<div class="substep__title">
    Hazardous Control Actions and Associated Safety & Security Constraints - {{$ca->name}}
</div>

<!--<div class="substep__add suggested-uca" id="suggested-ca-{{$ca->id}}">
    + Suggested Hazardous Control Actions
</div>  -->

<div class="substep__content" id="uca-{{$ca->id}}">

    <div class="container">

        <div class="container-fluid" style="margin-top: 10px">

            <div class="table-row header">
                <div class="text">Hazardous Control Actions&nbsp<i class="fa fa-question-circle" title="An Unsafe or Hazardous Control Action (UCA or HCA) is a control action that, in a particular context and worst-case environment, will lead to a hazard. (Adapted from STPA Handbook, p. 35)"></i></div>
                <div class="text">Associated Safety & Security Constraint&nbsp<i class="fa fa-question-circle" title="A controller constraint specifies the controller behaviors that need to be satisfied to prevent UCAs (STPA Handbook, p. 41)"></i></div>
                <div class="number-contexttable"><!-- Edit/Delete icons --></div>
            </div>



            @foreach(App\SafetyConstraints::where('controlaction_id', $ca->id)->orderby('id')->get() as $sc)
                <div class="table-row" id="uca-row-{{$sc->id}}">
                    
                    <div class="text">
                        
                        <br/>
                        <textarea class="uca_list_textarea" id="unsafe_control_action-{{$sc->id}}" disabled>{{$sc->unsafe_control_action}}</textarea>
                        
                        @if($sc->rule_id > 0)
                                <?php
                                    $rules = App\Rule::select('id')->where('controlaction_id', $ca->id)->orderby('id')->get();
                                    
                                    foreach($rules as $key => $rule){
                                        if($rule->id == $sc->rule_id){
                                            echo '<a class="uca_association" title="Generated by Rule '.($key+1) .'">R'. ($key + 1) .'</a>';
                                        }
                                    }
                                ?>
                        @endif

                        @foreach(App\RulesSafetyConstraintsHazards::where('sc_id', $sc->id)->get() as $rsch)
                            <?php
                                $h_name = App\Hazards::find($rsch->hazard_id)->name;
                            ?>
                            <a class="uca_association" title="{{$h_name}}">[H-{{$hazard_map[$rsch->hazard_id]}}]</a> 
                        @endforeach
                        <br/>
                        <br/>

                    </div>
                    
                    <div class="text">
                        <br/>
                        <textarea class="uca_list_textarea" id="safety_constraint-{{$sc->id}}" disabled>{{$sc->safety_constraint}}</textarea>
                    </div>

                    @if($sc->rule_id == 0)
                        <div class="content-uca">
                            <form class="edit-form" data-edit="uca" method="POST" style="display: inline-block; float: left;">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="hidden" name="controlaction_id" id="controlaction_id" value="{{$ca->id}}">
                                <input type="hidden" name="safety_constraint_id" id="safety_constraint_id" value="{{$sc->id}}">
                                <input type="image" src="{{ asset('images/edit.ico') }}" alt="Delete" width="20" class="navbar__logo">
                            </form>
                            <form action="/deleteuca" class="delete-form" data-delete="uca" method="POST" style="display: inline-block; float: left;">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="hidden" name="controlaction_id" id="controlaction_id" value="{{$ca->id}}">
                                <input type="hidden" name="safety_constraint_id" id="safety_constraint_id" value="{{$sc->id}}">
                                <input type="image" src="{{ asset('images/trash.png') }}" alt="Delete" width="20" class="navbar__logo">
                            </form>
                        </div>
                    @endif
                    
                </div>
            @endforeach

        </div>     

    </div>
    </br>
    <center>
        <form action="/deletealluca" method="POST" class="delete-all-uca">
                <input type="hidden" name="_token" value="{{csrf_token()}}">
                <input type="hidden" id="controlaction_id" name="controlaction_id" value="{{$ca->id}}">
                <button class="font-button" id="delete"><img src="/images/trash.png" class="steptwo-button" width="15"/> Delete all Hazardous Control Actions
        </button>
        </form>
    </center>
</div>